Messages:
  - "&f=============================="
  - "&d&lWelcome to &e&lYourServerName!"
  - ""
  - "&c&lShop: &ewww.shop.com"
  - "&c&lForums: &ewww.forums.com"
  - "&c&lSupport: &ewww.support.com"
  - ""
  - "&dHope you enjoy your time here!"
  - "&f=============================="