#Made by BGHDNetwork(Noodles)
#=======================================================
#Plugin Page: https://www.spigotmc.org/resources/46673
#=======================================================
Update:
  Enabled: true
#join.update
#Enables if there is a message on-join when the plugin is outdated. 
#=======================================================
CheckForUpdates:
  Enabled: true
#Enables a message in console if the plugin is outdated.
#=======================================================
Messages:
  Line0: '&f=============================='
  Line1: '&d&lWelcome to &e&lYourServerName!'
  Line2: ''
  Line3: '&c&lShop: &ewww.shop.com'
  Line4: '&c&lForums: &ewww.forums.com'
  Line5: '&c&lSupport: &ewww.support.com'
  Line6: ''
  Line7: '&dHope you enjoy your time here!'
  Line8: '&f=============================='
#=======================================================